### ISSUE TITLE
#docker + #MySQL 5.7 で、コンテナを終了・再起動してもデータが消えないように volume mount しながら port 指定でDBサーバーを作る  docker-compose の例

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#1076]
# ./docker-compose.yml

```yml
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "10000:3306"
```

# exe

通常実行

```
$ docker-compose up --detach db
```

バックグラウンド実行はこちら

```
$ docker-compose up --detach db
```

# MySQL への接続

```
$ mysql -u root -h 127.0.0.1 -P 10000
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.25 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

# 動作検証

db や テーブル作ってから docker compose down したり up したりして、データが残っていることを確認
