### ISSUE TITLE
#React で 簡単な汎用モジュール的なものを作って CSS の色を切り替えて遊ぶ ( #Codepen )

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#1378]
# とにかく

敷居を最小化する戦略でいこうぜ。

# [React on CodePen - React Patterns & Templates](https://codepen.io/topic/react/templates)

良さげな教材を選ぶ。

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/89618/11d675a5-d448-4c00-50a7-878f86295c39.png)

# Codepen

適当に自分が使いやすくしたもの。

[A Pen by yumainaura](https://codepen.io/yumainaura/pen/xeJqbV?editors=0110)
![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/89618/83206d02-63f8-0fa7-87aa-e51a086aeee5.png)

# ポイント

Boxという汎用モジュールを作っている

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/89618/291b5a91-8614-0fa4-2d6a-9b87fa525129.png)

# App Component から Box Component を3個呼び出している

colorMode を変えている

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/89618/fb25bc27-6640-0b30-84a6-76db08999235.png)

# CSS に colorMode を定義している

![image.png](https://qiita-image-store.s3.ap-northeast-1.amazonaws.com/0/89618/42c77fe5-14f6-f3dc-b8f7-3e53456aa60b.png)

colorMode = false の時は何も使われない、という動作ができるっぽい。

( #ruby のぼっち演算子にも似てる気がするな )

# js

```js
// This is how a function component takes props.
const Box = props => (
  <div className={`box ${props.colorMode}`}>
    <h1 className="title">{props.title}</h1>
  </div>
);

// This Class component also can have props
class App extends React.Component {

  render() {
    
    return <div>
      <h1 class="subtitle">
        {this.props.header}
      </h1>
      <Box
        colorMode="false"
        title="Light"
      />
      <Box
        colorMode="dark-mode"
        title="Dark"
      />
      <Box
        colorMode="orange-mode"
        title="Orange"
      />
    </div>;
  }
  
}


ReactDOM.render(<App header="Hello, Colors!"/>, document.getElementById("root"));
```

# css

```css
body {
  height: 100vh;
  margin: 0;
  display: grid;
  place-items: center;
  max-width: 250px;
  margin: 0 auto;
}
.box {
  width: 300px;
  &.dark-mode {
    background: black;
    color: #bbb;
    h1 {
      color: white;
    }
    .checkbox:hover {
      color: white;
    }
  }
  &.orange-mode {
    background: orange;
    color: red;
    h1 {
      color: red;
    }
    .checkbox:hover {
      color: red;
    }
  }
}
```
# HTML

```
<div id="root"></div>

```
