### ISSUE TITLE
#Rails + shoryuken gem + #AWS SQS で非同期のキューイング処理をする 

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#2419]
# shoryuken.yml

```yml
aws:
  access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             <%= ENV['AWS_REGION'] %>
concurrency: 1
queues:
  - example1
  - example2
  - example3
```

# ENV

```
export AWS_ACCESS_KEY_ID=XXXXXXXXXX
export AWS_SECRET_ACCESS_KEY=YYYYYYYYY
export AWS_REGION=us-east-2

```

# application.rb

```rb
require_relative 'boot'

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module RailsActiveJobExample
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 6.0

    config.active_job.queue_adapter = :shoryuken

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration can go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded after loading
    # the framework and any gems in your application.
  end
end

```

# app/jobs/sample_job.rb

```rb
class SampleJob < ApplicationJob
  queue_as :example2

  # shoryuken_options queue: 'sample', auto_delete: true, body_parser: :json

  def perform(*args)
    puts rand(9999999999999)
  end
end

```

# hello_worker.rb

```rb
class HelloWorker
  include Shoryuken::Worker

  shoryuken_options queue: 'example1', auto_delete: true
  shoryuken_options queue: 'example2', auto_delete: true
  shoryuken_options queue: 'example3', auto_delete: false

  def perform(sqs_msg, name)
    puts "Performed!"
    puts sqs_msg
    puts name
  end
end

```

# config ファイルなしでワーカーを起動する

キューは1個しか指定できないっぽい？

```
bundle exec shoryuken -q example2 -r ./hello_worker.rb
```

# config ファイルを指定してワーカーを起動する

```
bundle exec shoryuken -C config/shoryuken.yml -r ./hello_worker.rb
```

# ジョブの実行

rails console などでジョブを投げる
