### ISSUE TITLE
docker-compose build が重い、イメージサイズが大きすぎるのって .dockerignore で解決できる？ #docker #rails

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#2713]
# .dockeriignore

噂に聞いた話レベルだが、本当に効果があった。

.docker-compse.yml と同じディレクトリに .dockerignore を設置して、不必要なディレクトリを無視してやる。

```
/log
/vender
```

まだ概要把握中。

# 別の方法？

logディレクトリなどをマウントしない方法もあるみたいだけど、これだとマウントされなくなってしまうしな。

[docker-composeを爆速にする - Qiita](https://qiita.com/shotat/items/57d049793605ffc20135)

>Rails開発等でdocker-composeを使うと非常に遅い場合があります（特にDocker For Mac）。
docker-compose時に余計なファイルをマウントしてしまってるのが原因らしいので、.git, log, tmp, vendor >などのホストからマウントする必要のないディレクトリを別のvolumeでマウントを上書きしてしまえば解消されます。

```yml
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_POSTGRES_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
      # 1. exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
...
```

# 関連

[Dockerfile リファレンス — Docker-docs-ja 17.06.Beta ドキュメント](http://docs.docker.jp/engine/reference/builder.html#dockerignore-file)

[docker-compose build too slow (not response) · Issue #6409 · docker/compose](https://github.com/docker/compose/issues/6409)

[.dockerignore アンチパターン - Qiita](https://qiita.com/munisystem/items/b0f08b28e8cc26132212)
