### ISSUE TITLE
docker-compose で 複数の Dockerfile をまたいで build できるのだろうか？ ベースイメージを作成しておきたい #docker

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#2720]
# docker-compose でこんなことがやりたい

- Dockerfile からオリジナルのイメージを build する
- オリジナルのイメージを元に Dockerfile を作成してそれを docker-compose で使う

以下はイメージ

```yml
version: '3'

services:
 base-service:
    build: base-dir
    as: some_base_iimage # 架空の指定
 child-service:
    build: child-dir
```

# base-dir/Dockerfile

```
FROM alpine
...
```

# child-dir/Dockerfile

```
FROM some_base_iimage
...
```

# 解決1

シェルスクリプトを使ってbuildするようにする

`./build.sh`

```bash
cd other-dir && docker build -t  . some_base_image && cd -
docker-compose build
```

こんなんで良いだろうか

そもそも docker-compose の仕組みに乗れるかどうか分からないので

docker-compose は全ての docker image が揃っていることを前提に作られているのでは？

# 解決2

Dockerhub にレポジトリとイメージを作成しておく
いちど固めておけば online から取れるよね
