### ISSUE TITLE
docker-compose で 環境変数で port を切り替える例 ( #docker )

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3077]
# docker-copose.yml

- 変数を指定する
- docker container の 3000 が expose されている状態
- デフォルトでは 4000番 port を外部に公開する例

```
version: '3.0'

services:
  app:
    ...(色々省略)...
    ports:
      - ${APP_PORT:-4000}:3000
```

# .env 

.env ファイルに以下を設定

APP_PORT=5000

# 実行

```
docker-compose up
```
