### ISSUE TITLE
docker – mysql コマンドでローカルから接続できない ( Can't connect to local MySQL server through socket '/tmp/mysql.sock'  )

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3344]
# エラー

```
$ mysql -u root -P 9999
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

# docker-compose.yml

```yaml
version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "9999:3306"
```

# 解決

ホストを指定したら接続できた

```
$ mysql -h 127.0.0.1 -u root -P 9999

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.32 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

# チャットメンバー募集

何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ

# Twitter

https://twitter.com/YumaInaura
