### ISSUE TITLE
AWS ECS – CODE DEPLOY のエラー

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3423]
# An AppSpec file is required, but could not be found in the revision

レポジトリトップに app.yml を置いてあるのにないと言われる

buildspec.yml の artifacts に指定して解決した

```yml
artifacts:
  files:
    - appspec.yml
```
