### ISSUE TITLE
Github Actions - Setup Ruby で キャッシュバージョンを指定する

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3475]
# 公式

https://github.com/ruby/setup-ruby

# 例

cache-versionを指定すれば良いようだ
ただ非推奨らしい

```yml
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        cache-version: 'XXXX'
```
