### ISSUE TITLE
Github Actions の setup-ruby で新規PR作成時にもキャッシュを有効にしたい

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3476]
# 公式

https://github.com/ruby/setup-ruby

# 例

cache-versionを指定すれば良いようだ
ただ非推奨らしい

```yml
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        cache-version: 'XXXX'
```

# 生成されるキャッシュの確認

Githubレポジトリで Actions > Caches で確認できる

バージョン指定なしの場合に生成されるキャッシュ

```
(色々省略)/api-with--without--only---Gemfile.lock-(Gemfile.lockをハッシュ化した値)
```

バージョン指定ありの場合に生成されるキャッシュ

```
(色々省略)/api-with--without--only--v-XXXX-Gemfile.lock-(Gemfile.lockをハッシュ化した値)
```
