### ISSUE TITLE
CI – Playwright + Github Actions で E2Eテストを実行する例 ( フロント + バックエンドAPI構成 ) ( Httpレスポンスにモックを使わない )

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3603]
```yml
name: Playwright Test

on: [pull_request]

jobs:
  play:
    runs-on: ubuntu-latest
    services:
      # データベースサーバーの起動
      mysql:
        image: mysql:x.x.x
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ruby for Backend API
        uses: ruby/setup-ruby@v1
        with:
          working-directory: rails-dir
          ruby-version: .ruby-version
          bundler-cache: true

      # 何らかの方法でテストに必要なデータベースとその初期データを作成する
      # この例ではRailsのマイグレーションとseedを使う
      - name: Create Database
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed

      # バックエンドAPIを起動
      - name: Start Backend API On Background
        run: |
          bin/rails server -d -p 4000

      # APIの起動を待ち受ける
      - name: Wait Backend API Response
        run: |
          curl --retry 5 --max-time 5 http://localhost:4000

      - name: Setup node for Front 
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies for Front
        run: npm install

      # フロントを起動
      - name: Start Front on Background
        run: |
          npm run build
          nohup npm run start &

      # フロントのの起動を待ち受ける
      - name: Wait Front Response
        run: |
          curl --retry 5 --max-time 5 http://localhost:3000

      # Playwrightでスクリーンショットを撮る場合は日本語文字化け対策
      - name: Install fonts-noto
        run: sudo apt install fonts-noto-cjk

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      # Playwrightテストを実行する
      - name: Playwright Tests
        run: |
          npx playwright test flow_A_step_1.spec.ts
          npx playwright test flow_A_step_2.spec.ts
          bin/rails db:migrate:reset 
          bin/rails db:seed
          npx playwright test flow_B.spec.ts

```
