### ISSUE TITLE
Github Actions + reg suit で snapshot key が検知できない場合

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3604]
# Error

```
[reg-suit] warn Failed to detect the previous snapshot key
[reg-suit] info Skipped to fetch the expected data because expected key is null.
```

# 対応

checkout でfetch-depth を指定して、全てのヒストリーとコミットを参照できるようにしておけば良かったようだ
もしくは適当に大きな数字を指定しても成り立つかもしれない

> Number of commits to fetch.
> 0 indicates all history for all branches and tags.

https://github.com/actions/checkout

```yml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
```
