### ISSUE TITLE
Github Actions – Playwright で利用する ブラウザ Chromium をキャッシュ利用する

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3608]
# Workflowの例 (一部)

```yml
- name: Restore Cache Playwright Browser
  id: restore-cache-playwright-chromium
  uses: actions/cache/restore@v4
  with:
    path: /home/runner/.cache/ms-playwright
    key: playwright-chromium-$(npx playwright --version | sed 's/ //g')

- name: Install Playwright Browsers
  run: npx playwright install chromium
  if: ${{ steps.restore-cache-playwright-chromium.outputs.cache-hit != 'true' }}

- name: Save Cache – Playwright Browser
  uses: actions/cache@v4
  id: save-cache-playwright-chromium
  with:
    path: /home/runner/.cache/ms-playwright
    key: ${{ steps.restore-cache-playwright-chromium.outputs.cache-primary-key }}
```
