### ISSUE TITLE
Github Actions – Font Noto をキャッシュする

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3610]
```yml
jobs:
  web-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Restore or Save Cache – Font Noto
        id: cache-font-noto
        uses: actions/cache@v4
        with:
          path: /usr/share/fonts/opentype/noto
          key: font-noto-cache-key

      - name: Install fonts-noto
        run: sudo apt install fonts-noto-cjk
        if: ${{ steps.cache-font-noto.outputs.cache-hit != 'true' }}

```
