### ISSUE TITLE
docker compose での環境変数切り替えは .env ファイルではなく 直接記述した方が分かりやすいんじゃ

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3662]
# 例

```yml
version: '3.8'
services:
  xxx_service:
    ...
    environment:
      # docker compose up 実行時に環境変数指定できるもの
      # ブレースの中は ${localで指定可能な環境変数名:-無指定の場合の固定値} という記法
      - 'XXX_ENV=${XXX_ENV:-foo}'
      # docker compose up 実行時に環境変数指定させていない固定値のもの
      - 'YYY_ENV=bar'
```

このように書いておけば

`XXX_ENV=yeah docker compose up`

のようにコマンドレベルで環境変数指定が出来るので、何かと使いやすい気がする

# 旧来の例

```yml
version: '3.8'
services:
  xxx_service:
    ...
    env_file:
      - .env.development
```

`.env.development` のように環境変数指定用のファイルを読み込ませておいて、そのファイル自体は gitignore しておく運用を多く見かける

だがこの方法だとファイルの状態によって開発者間で環境の差異が生じたり、どこで環境変数をコントロールしているのかがわかりづらかったり、という欠点がある

# チャットメンバー募集

何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ

# プロフィール・経歴

https://github.com/YumaInaura/YumaInaura
