### ISSUE TITLE
AWS AMI で作成した Redash を v8 から v10.1 にアップグレード

### ISSUE THREAD

**Issue by YumaInaura** [YumaInaura/YumaInaura#3860]
# 公式

以下などを参照

https://github.com/getredash/redash/releases/tag/v10.0.0

# 手順

EC2サーバーにssh接続して、以下の手順をとる

```
sudo su -
```

```
cd /opt/redash/
```

```
vim docker-compose.yml
```

docker compose を以下に書き換える

```yaml
version: "2"
x-redash-service: &redash-service
  image: redash/redash:10.1.0.b50633
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
```

```
docker-compose stop server scheduler scheduled_worker adhoc_worker
```

```
docker-compose up --force-recreate --build
```

```
docker-compose run --rm server manage db upgrade
```

```
docker-compose up -d
```

# チャットメンバー募集

何か質問、悩み事、相談などあればLINEオープンチャットもご利用ください。

https://line.me/ti/g2/eEPltQ6Tzh3pYAZV8JXKZqc7PJ6L0rpm573dcQ

# プロフィール・経歴

https://github.com/YumaInaura/YumaInaura
